name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::146121144646:role/GitHubActionsDeployRole

      - name: Upload Spark jobs to S3
        run: aws s3 sync ./jobs s3://my-emr-etl-bucket-poc/jobs/
