name: Terraform EMR ETL
on: workflow_dispatch

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }

      - name: Upload job to S3
        run: aws s3 cp jobs/poc_etl_job.py s3://my-emr-etl-bucket-poc/jobs/poc_etl_job.py

      - name: Terraform init/plan/apply
        working-directory: infra
        env:
          TF_VAR_emr_service_role: EMR_DefaultRole
          TF_VAR_emr_ec2_role: EMR_EC2_DefaultRole
          TF_VAR_subnet_id: subnet-06ea10d2d2e7afb5f
          TF_VAR_master_sg: sg-0df472a0546e4cb57
          TF_VAR_core_sg: sg-0c757b1c82c8674b1
          TF_VAR_log_bucket: aws-logs-146121144646-us-west-2
          TF_VAR_code_bucket: my-emr-etl-bucket-poc
        run: |
          terraform init
          terraform plan -out tfplan
          terraform apply -auto-approve tfplan
